name = "news-agent"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# 环境变量通过 wrangler secret 命令设置
# 部署前运行: wrangler secret put DEEPSEEK_API_KEY

[env.production]
name = "news-agent-prod"

[env.staging]
name = "news-agent-staging"
